["Custom Dimensions Config"]
	dimensions_settings = ["000/075/minecraft:overworld", "050/100/minecraft:the_nether", "100/200/minecraft:the_end", "020/050/the_bumblezone:the_bumblezone", "005/010/twilightforest:twilight_forest"]
