
["Custom Dimensions Config"]
	#(min/max/dimensionName) Make sure levels are written in 3 digits, e.g. (005/010/twilightforest:twilight_forest) in this example, you will limit the spawning level for the twilight forest to level 5 and level 10.
	dimensions_settings = ["[min]0[minEnd][max]75[maxEnd]minecraft:overworld", "[min]50[minEnd][max]100[maxEnd]minecraft:the_nether", "[min]100[minEnd][max]200[maxEnd]minecraft:the_end", "[min]20[minEnd][max]50[maxEnd]the_bumblezone:the_bumblezone", "[min]5[minEnd][max]10[maxEnd]twilightforest:twilight_forest"]

